FROM akorn/luarocks:lua5.1-alpine AS build

RUN apk add make gcc libc-dev git openssl-dev


# This dependency is needed on Lua 5.1/5.2 but fails on 5.4,
# hence install separately
RUN luarocks install luabitop

# copy the local repo contents and build it
COPY ./ /tmp/homie-p1
RUN cd /tmp/homie-p1 && luarocks make



FROM akorn/lua:5.1-alpine
RUN apk add --no-cache openssl ca-certificates socat

# define env vars
ENV P!_SOCAT_INPUT="/dev/ttyUSB0,b115200"
ENV HOMIE_MQTT_URI="mqtt://mqtthost:1883"
ENV HOMIE_DOMAIN="homie"
ENV HOMIE_DEVICE_ID="homiep1"
ENV HOMIE_DEVICE_NAME="P1 smartmeter reader"
ENV HOMIE_LOG_LOGLEVEL="info"

# copy luarocks tree and data over
COPY --from=build /usr/local/lib/lua /usr/local/lib/lua
COPY --from=build /usr/local/share/lua /usr/local/share/lua
COPY --from=build /usr/local/lib/luarocks /usr/local/lib/luarocks
# copy the command as generated by LuaRocks
COPY --from=build /usr/local/bin/homiep1 /usr/local/bin/homiep1

CMD ["homiep1"]
